services:
  postgres:
    image: postgres:15
    container_name: bookstore_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ranit
      POSTGRES_DB: bookstore
    ports:
      - '8001:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: