services:
  postgres:
    image: postgres:15
    container_name: bookstore_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ranit
      POSTGRES_DB: bookstore
    ports:
      - '8001:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore_app
    restart: always
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env

volumes:
  postgres_data: